import React from 'react';
import { ArrowLeft, Scale } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300 p-6 md:p-12 font-sans overflow-y-auto">
      <div className="max-w-3xl mx-auto">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-500 hover:text-white transition-colors mb-8 group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          Back to Portal
        </button>

        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 bg-cyan-500/20 rounded-xl">
            <Scale className="w-8 h-8 text-cyan-400" />
          </div>
          <h1 className="text-4xl font-extrabold text-white tracking-tight">Terms of Service</h1>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-slate-400">
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-100">1. Acceptance of Terms</h2>
            <p>
              By accessing ReFURRM L'INK, you agree to be bound by these terms. This platform is provided as an advanced 
              repository analysis tool for developers and engineering teams.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-100">2. Use of AI</h2>
            <p>
              The analysis provided is generated by AI models. While we strive for extreme accuracy in logic mapping, 
              users should verify critical security findings manually before implementing production changes.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-slate-100">3. User Responsibility</h2>
            <p>
              You are responsible for the API keys you provide and the access you grant to third-party repositories. 
              ReFURRM L'INK is not liable for costs incurred on your personal AI billing accounts.
            </p>
          </section>

          <section className="pt-8 border-t border-white/5">
            <p className="text-[10px] uppercase tracking-widest font-mono">Effective Date: May 2026</p>
          </section>
        </div>
      </div>
    </div>
  );
};
